services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_DB: tmc
      POSTGRES_PASSWORD: postgresP
    user: postgres
    ports:
    - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, pg_isready, -U, postgres]
      interval: 3s
      timeout: 3s
      retries: 10
  backend:
    image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
    build:
      context: ./backend
    depends_on:
    - postgres
    healthcheck:
      test: [CMD, curl, -f, http://backend:8000/]
      interval: 2s
      timeout: 2s
      retries: 5
  app:
    container_name: frontend
    depends_on:
    - backend
    build:
      context: ./app
    ports:
    - 5173:5173
    volumes:
    - ./app:/app
    - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
    command: npm run dev -- --host

volumes:
  postgres_data:
